export const SIGNALS = {
	SIGINT: 'SIGINT',
	SIGTERM: 'SIGTERM',
	SIGKILL: 'SIGKILL',
	SIGQUIT: 'SIGQUIT',
	SIGABRT: 'SIGABRT',
	SIGALRM: 'SIGALRM',
	SIGBREAK: 'SIGBREAK',
	SIGFPE: 'SIGFPE',
	SIGILL: 'SIGILL',
} as const;
